model_family: qwen3_5
model_name_or_path: iapp/ChindaMT-0.8B
generator_name: chindamt-0.8b
mode: hf

inference:
  max_new_tokens: 1024
  temperature: 0.01
  top_p: 0.7
  top_k: 20
  repetition_penalty: 1.05
  batch_size: 32
